### PR TITLE
Add thread count setting

### PR DESCRIPTION
**Pull request by apage43**
dogstory

Closes https://github.com/nomic-ai/gpt4all-chat/issues/67

### CODE REVIEW

**Comment by apage43** [comment]
removed restore default behavior for threadcount as I don't have access to the default for the model until the model is actually loaded (leaving it up to the model to decide its own default concurrency) and its not really a generation parameter anyway

**Comment by manyoso** [comment]
Can you rebase and fix the conflicts?

**Comment by manyoso** [comment]
This is looking great, but I have one concern. LLM and LLMObject live in different threads and the thread count is not protected by a mutex. I don't think you should add a mutex. Rather, I think you should hook it up the same way I do with LLM calling a 'requestThreadCountChange()' signal that is hooked up to LLMObject. We can discuss in discord how it works.

**Comment by apage43** [comment]
Setting now happens on the LLM thread - this does remove the accidental but fun behavior of the text generation speeding up and slowing down in real time though, since now the thread count only changes at the end of a prompt

**Pull request merged**
